## To see all available configs, please check the documentation
## https://github.com/TerraHubCorp/terrahub/tree/master/docs
## project config
project:
  name: 'brettcave/terraworld'
  code: '5642dcd4'
  include:
    - '.'
  exclude:
    - '**/.terraform/**'
    - '**/node_modules/**'
    - '**/.git/**'

## terraform config
terraform:
  varFile:
    - 'default.tfvars'
